### ISSUE TITLE
Подбор референсов / Создание скетчей для интерфейса игры и чипов

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#10]
[Таблица с описанием чипов](https://docs.google.com/spreadsheets/d/1IwOZjvVZVZigGjYOXM2lv2WmqdgTExgJLGgjHsPbXUU/edit#gid=1850673203)

**Дедлайн: 24.03 12:00**

Отправить ссылку Figma с референсами/скетчами ↓↓↓

**Comment by RinaPanu** [comment]
https://www.figma.com/file/VPI4WcTFx497ZMatFcenk5/UI?type=design&node-id=0%3A1&mode=design&t=tK1y4TaA9NChrvLV-1
