### ISSUE TITLE
Подбор референсов / Создание скетчей для отсеков

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#11]
[Таблица с описанием отсеков](https://docs.google.com/spreadsheets/d/1IwOZjvVZVZigGjYOXM2lv2WmqdgTExgJLGgjHsPbXUU/edit#gid=980873999)

**Дедлайн: 24.03 12:00**

Отправить ссылку Figma с референсами/скетчами ↓↓↓

**Comment by Vedro12** [comment]
https://www.figma.com/file/cfaEyB89EjGftgroYxL1iM/%D1%81%D0%BA%D0%B5%D1%82%D1%87%D0%B8?type=design&node-id=0%3A1&mode=design&t=btJu3ImJI3ft12Wm-1
