### ISSUE TITLE
Подбор референсов / Создание скетчей для оружия

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#12]
[Таблица с описанием оружия](https://docs.google.com/spreadsheets/d/1IwOZjvVZVZigGjYOXM2lv2WmqdgTExgJLGgjHsPbXUU/edit#gid=0)

**Дедлайн: 24.03 12:00**

Отправить ссылку Figma с референсами/скетчами  ↓↓↓

**Comment by WatchWitch** [comment]
https://www.figma.com/file/SFaXUsu1hoaKBCkIMTTaWx/%D0%94%D0%BE%D0%B1%D1%80%D1%8B%D0%BD%D0%B8%D0%BD%D0%B0-%D0%9A.-%D0%BE%D1%80%D1%83%D0%B6%D0%B8%D0%B5?type=design&node-id=0%3A1&mode=design&t=dswbCNWXr861HlcC-1
