### ISSUE TITLE
Создание уровней

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#15]
Создание схемы уровня с местами спавна предметов/врагов.
По 2 уровня на [каждый](https://docs.google.com/spreadsheets/d/1IwOZjvVZVZigGjYOXM2lv2WmqdgTExgJLGgjHsPbXUU/edit#gid=980873999) отсек кроме отсеков 7-9. Для отсеков 7-9 - один уровень

**Дедлайн: 31.03 12:00**

**Comment by AlinaBasyrova** [comment]
https://www.figma.com/file/ZklEebRcJb9HxTXB0tfkfY/%D0%9A%D0%B8%D0%B2%D0%B8%2C-%D1%88%D1%82%D1%83%D0%BA%D0%B8-%D0%B4%D0%BB%D1%8F-%D0%B2%D0%B4%D0%BE%D1%85%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F?type=design&node-id=75-15737&mode=design&t=XnCRdXBF7Kj4HtBe-4
