### ISSUE TITLE
Нарисовать иконки перманентных усилений

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#21]
Нарисовать иконки для всех усилений из [этого](https://docs.google.com/spreadsheets/d/1IwOZjvVZVZigGjYOXM2lv2WmqdgTExgJLGgjHsPbXUU/edit#gid=96999009) списка.
Размер иконки: 256x256

**Дедлайн: 31.03 12:00**

**Comment by RinaPanu** [comment]
https://www.figma.com/file/VPI4WcTFx497ZMatFcenk5/UI?type=design&node-id=0%3A1&mode=design&t=j7M9wYOmwFEQOHdc-1
нарисовала иконки, но с цветами планирую ещё играться. Плюс с другими художниками хочу согласовать пару моментов. И ещё над оформлением рывка подумать хочется
