### ISSUE TITLE
Отрисовка врагов

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#25]
Нарисовать всех врагов из [этого](https://docs.google.com/spreadsheets/d/1IwOZjvVZVZigGjYOXM2lv2WmqdgTExgJLGgjHsPbXUU/edit#gid=1526837299) списка.

Дедлайн: 7.04 12:00

**Comment by WatchWitch** [comment]
Общая фигма художников: 
https://www.figma.com/file/cfaEyB89EjGftgroYxL1iM/%D1%81%D0%BA%D0%B5%D1%82%D1%87%D0%B8?type=design&node-id=137%3A2&mode=design&t=1D09bW8T40Wa6CsC-1

Моя фигма: 
https://www.figma.com/file/SFaXUsu1hoaKBCkIMTTaWx/%D0%94%D0%BE%D0%B1%D1%80%D1%8B%D0%BD%D0%B8%D0%BD%D0%B0-%D0%9A.-Props?type=design&node-id=65%3A2&mode=design&t=v4ETYcYBZevOiRmp-1

И там, и там одно и то же
