### ISSUE TITLE
Подобрать звук для игры

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#29]
Подобрать звуки/музыку для всей игры

Отправить музыку [сюда](https://drive.google.com/drive/u/1/folders/11GJeb5qo2FAhT3fBLW-M4dnl7VTeSh20)

**Comment by AlinaBasyrova** [comment]
Нет доступа на добавление файлов 
https://drive.google.com/drive/folders/1izu4qdH9x8R3JWKxfCv6HprGAacCAKZ4?usp=sharing
