### ISSUE TITLE
Создать мокап экраны в выбранной стилистике

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#4]
Каждый отрисовывает несколько экранов игры ([пример 1](https://www.figma.com/file/FtCCVvvE7PFN6PUjOVdnEP/%D0%91%D0%B0%D1%81%D1%8B%D1%80%D0%BE%D0%B2%D0%B0-%D0%90.%D0%A0.?type=design&node-id=33-4&mode=design&t=3JRjRshlCCsh6Fyw-0), [пример 2](https://www.figma.com/file/1nkAaePhN8xnfSBez2Lb05/%D0%94%D0%BE%D0%B1%D1%80%D1%8B%D0%BD%D0%B8%D0%BD%D0%B0-%D0%9A%D1%81%D0%B5%D0%BD%D0%B8%D1%8F%2C-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0-138?type=design&node-id=1-5&mode=design&t=WtCBdgPNXMqupEKc-0)), после команда художников обсуждает стиль и выводить правила его создания

**Дедлайн: 17.03 12:00**

**Comment by WatchWitch** [comment]
https://www.figma.com/file/oWGtRgYDt3SMCuEQPMiofI/%D0%94%D0%BE%D0%B1%D1%80%D1%8B%D0%BD%D0%B8%D0%BD%D0%B0-%D0%9A.-Spaceship-%D0%BC%D0%BE%D0%BA%D0%B0%D0%BF-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D1%8B?type=design&node-id=0%3A1&mode=design&t=g8xe4QaYEnfILPJv-1
