### ISSUE TITLE
Написание концепт-документа #2

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#5]
Написать подробнее о врагах:
- Имя
- Визуальное описание для художников
- Референс (если есть)

Написать алгоритм генерации уровня:
- Есть ли обязательные отсеки в каждом уровне?
- Как выбирать варианты следующей локации?
- Как выбирать варианты новых чипов?
- Связаны ли чипы с определённым типом локации?

Написать подробнее про механику кислорода:
- Начальное значение? 
- Сколько тратиться кислорода за секунду (минуту) игры?
- Как игроку восстановить кислород в оранжерее/безопасной зоне? 
- Можно ли восстановить кислород в других зонах?
- Врагам нужно восстанавливать кислород?

Написать про экономику игры: 
- Как находить монеты? 
- Что такое магазин? Основные функции? 
- Как именно улучшаются чипы в инженерном отсеке? 
- _Почему на захваченном космическом корабле кто-то продаёт оружие? Почему на захваченном космическом корабле вообще работает экономика?_

Написать про чипы:
- Сюжетное объяснение: как именно работают эти чипы? Есть какие-то слоты в костюме/голове игрока? Враги используют чипы?
- Как выглядит улучшение чипов?
- Если можно улучшить чипы, почему нельзя улучшить оружие?

Создать прохождения схему демо-версии игры:
- Блок схема прохождения игры
- Сюжет: персонажи (визуальное описание для художников), описание сюжета
- Составить итоговый список всех механик игры (отобразить в блок схеме использование каждой механики)

**Дедлайн: 24.03 12:00**

**Comment by AlinaBasyrova** [comment]
Краткий отчет

Написать алгоритм генерации уровня:
1 - 3. Диз-док п. генерация уровня
4. Нет

Написать подробнее про механику кислорода:
1. 100%, 300 пунктов на старте
2. 1 пункт в секунду, 5 минут в сумме без улучшений (скорее всего нужно будет изменить, точно сказать можно только попробовав на практике)
3. В безопасных зонах (оранжерее и оружейном отсеке) потребление кислорода прекращается на время. Для восстановления кислорода нужно использовать предмет кислородным баллон в оранжерее. Его использование полностью восстанавливает шкалу
4. Восстанавливать кислород можно только используя кислородный балон. На данный момент он может находится только в оранжерее. 
5. Нет

Написать про чипы:
1. См диз-док п. чипы, враги их не используют
3. Ответ сюжетный: гг хорошо разбирается в чипах и может их модифицировать, а вот оружие это не его специализация. Да и как он улучшит какой-то кусок трубы? Ответ геймплейный: в целях чуть более простой балансировки, но идея принята на рассмотрение. 

Написать про экономику игры:
1. Выпадают при убийстве противников, тайник в секретной комнате, разрушаемые предметы на карте(? далеко не самый обязательный элемент игры, можно пока оставить)
2. Увеличиваем уровень чипа на инженерном столе(характеристики чипов на разных уровнях указаны в таблице через /)
3. Заменила монеты на эссенцию врагов. Мы как бы изучаем их и улучшаем свои навыки против них. Нпс в оружейной - не член экипажа, подозрительный тип, которому зачем-то нужна эта эссенция.
