### ISSUE TITLE
Нарисовать анимации для врагов #2

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#65]
Нарисовать анимации для [врага C](https://docs.google.com/spreadsheets/d/1IwOZjvVZVZigGjYOXM2lv2WmqdgTExgJLGgjHsPbXUU/edit#gid=1526837299&range=A5:K5)

**Comment by WatchWitch** [comment]
в общей фигме https://www.figma.com/file/cfaEyB89EjGftgroYxL1iM/%D1%81%D0%BA%D0%B5%D1%82%D1%87%D0%B8?type=design&node-id=137%3A2&mode=design&t=xxvqJeWlsE06uOim-1
