### ISSUE TITLE
Нарисовать анимацию для игрока #2

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#66]
Анимации:
- Бездействие
- Перемещение
- Прыжок
- Атака (кулаки)
- Анимация рук для каждого оружия _(как персонаж держит оружие)_
- Перемещение по лестнице
- Прыжок с лестницы
- Смерть

**Comment by WatchWitch** [comment]
в общей фигме https://www.figma.com/file/cfaEyB89EjGftgroYxL1iM/%D1%81%D0%BA%D0%B5%D1%82%D1%87%D0%B8?type=design&node-id=137%3A2&mode=design&t=xxvqJeWlsE06uOim-1
