### ISSUE TITLE
Написать описание для страницы игры

### ISSUE THREAD

**Issue by D9eka** [D9eka/Kiwi#68]
- **Краткое описание игры** —  до 150 знаков. Отображается в карточке игры в каталоге при наведении курсора.  

- **Полное описание игры** —  до 500 знаков и не совпадать с кратким описанием. Отображается на странице игры под баннером.  Для того, чтобы мы лучше поняли, что у Вас за игра, постарайтесь ответить на вопросы:
- Фактическая или предполагаемая дата выхода игры
- Формат монетизации игры (платная игра или free-to-play)
- На какие рынки нацелена игра? Какие языки поддерживает?

- **Об игре** — текст, отличный от краткого и полного описания, объемом до 10 000 знаков. Отображается на странице игры в качестве полного описания.

[Подробнее](https://documentation.vkplay.ru/p2p_vkp/p2p_setups_vkp)

**Comment by AlinaBasyrova** [comment]
Краткое описание: 
Космическая экспедиция пошла не по плану и теперь вам придется заново изучать собственный корабль, чтобы вернуть его на верный курс. 

Полное описание: 
Warp Trap - захватывающий рогалик, переносящий игроков в гипотетическое будущее, где человечество освоило перемещение с помощью варп-двигателей. Несмотря на их огромное преимущество перед классическими способами перемещения в космосе, использование варп-двигателей сопряжено с огромными рисками. Во время одного из перемещений варп-двигатель на корабле главного героя неожиданно повреждается, что приводит к серии аномалий.

**Comment by AlinaBasyrova** [comment]
Об игре: 
В гипотетическом будущем люди научились создавать варп-двигатели, что стимулировало активное исследование планет за пределами нашей солнечной системы. Однако новая технология все еще не полностью изучена, и неосторожное использование варп-двигателей может привести к трагическим последствиям. Впрочем главный герой, как и многие другие космические исследователи, готов пойти на этот риск.

Или он так думал. Все изменится, когда варп-двигатель на корабле действительно выйдет из строя, часть команды исчезнет, а корабль внезапно окажется заполнен ранее невиданными монстрами. Главному герою предстоит научится ориентироваться в этом хаосе, чтобы найти способ все исправить.

Warp Trap - увлекательный 2D рогалик в космическом сеттинге. Исследуйте постоянно меняющийся корабль, сражайтесь с монстрами и найдите способ починить варп-двигатель, чтобы вернуться домой. Но не теряйте времени, ведь кто знает, что может произойти, если вы застрянете здесь слишком надолго.
